export { default as useLocationInfo } from './useLocationInfo'
export { default as useMobileDevice } from './useMobileDevice'
export { default as useCopySelector } from './useCopySelector'
export { default as useCopyContent } from './useCopyContent'
export { default as useGetUrlParam } from './useGetUrlParam'
export { default as useDynamicLoadScript } from './useDynamicLoadScript'
export { default as useToggleFullScreen } from './useToggleFullScreen'
export { TouchBottomClass } from './useScrollToBottom'
export { default as useScrollToBottom } from './useScrollToBottom'

export { default as useGetLocalKey } from './useGetLocalKey'
export { default as useSetLocalKey } from './useSetLocalKey'
export { default as useClearLocal } from './useClearLocal'
export { default as useRemoveLocalKey } from './useRemoveLocalKey'
export { default as useGetBrowserInfo } from './useGetBrowserInfo'